#!/usr/bin/env bash
# Configures a ufw firewall that will block all incoming traffic
#+ except for TCP ports 22, 443 and 80.

sudo apt update
sudo apt install ufw
sudo ufw enable
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw default allow outgoing
sudo ufw reload
sudo ufw status
